[phases.setup]
nixPkgs = ["python311", "ffmpeg", "git"]
nixLibs = ["zlib", "libffi", "openssl"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p downloads",
    "chmod 755 downloads"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 1 --timeout 300 --keep-alive 30 --max-requests 1000 --max-requests-jitter 50 --preload main:app"